apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ham4bywr4-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ham4bywr4-java-quarkus-gitops